const std = @import("std");

pub fn calcExprSource(allocator: std.mem.Allocator) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(allocator);
    const w = out.writer(allocator);

    try w.writeAll("pub const CalcExpr = struct {\n");
    try w.writeAll("    const Self = @This();\n");
    try w.writeAll("    pub const Unit = enum { px, em, rem, percent };\n");
    try w.writeAll("    pub const Op = enum { add, sub, mul, div };\n");
    try w.writeAll("    pub const Kind = enum { unit, number, raw, op };\n");
    try w.writeAll("\n");
    try w.writeAll("    pub const Node = struct {\n");
    try w.writeAll("        kind: Kind,\n");
    try w.writeAll("        unit: Unit = .px,\n");
    try w.writeAll("        value: f32 = 0,\n");
    try w.writeAll("        text: []const u8 = \"\",\n");
    try w.writeAll("        lhs: u8 = 0,\n");
    try w.writeAll("        rhs: u8 = 0,\n");
    try w.writeAll("        op: Op = .add,\n");
    try w.writeAll("    };\n");
    try w.writeAll("\n");
    try w.writeAll("    nodes: [32]Node = undefined,\n");
    try w.writeAll("    len: u8 = 0,\n");
    try w.writeAll("    root: u8 = 0,\n");
    try w.writeAll("\n");
    try w.writeAll("    fn leaf(node: Node) Self {\n");
    try w.writeAll("        var self: Self = undefined;\n");
    try w.writeAll("        self.nodes[0] = node;\n");
    try w.writeAll("        self.len = 1;\n");
    try w.writeAll("        self.root = 0;\n");
    try w.writeAll("        return self;\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    fn unitLeaf(unit: Unit, value: f32) Self {\n");
    try w.writeAll("        return leaf(.{ .kind = .unit, .unit = unit, .value = value });\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    fn numberLeaf(value: f32) Self {\n");
    try w.writeAll("        return leaf(.{ .kind = .number, .value = value });\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    fn rawLeaf(text: []const u8) Self {\n");
    try w.writeAll("        return leaf(.{ .kind = .raw, .text = text });\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn px(value: f32) Self {\n");
    try w.writeAll("        return unitLeaf(.px, value);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn em(value: f32) Self {\n");
    try w.writeAll("        return unitLeaf(.em, value);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn rem(value: f32) Self {\n");
    try w.writeAll("        return unitLeaf(.rem, value);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn percent(value: f32) Self {\n");
    try w.writeAll("        return unitLeaf(.percent, value);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn raw(text: []const u8) Self {\n");
    try w.writeAll("        return rawLeaf(text);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn number(value: f32) Self {\n");
    try w.writeAll("        return numberLeaf(value);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    fn combine(self: Self, other: Self, op: Op) Self {\n");
    try w.writeAll("        var out = self;\n");
    try w.writeAll("        if (out.len + other.len + 1 > out.nodes.len) @panic(\"calc expression too complex\");\n");
    try w.writeAll("        var i: usize = 0;\n");
    try w.writeAll("        while (i < other.len) : (i += 1) out.nodes[out.len + i] = other.nodes[i];\n");
    try w.writeAll("        const lhs: u8 = out.root;\n");
    try w.writeAll("        const rhs: u8 = @intCast(out.len + other.root);\n");
    try w.writeAll("        out.nodes[out.len + other.len] = .{ .kind = .op, .op = op, .lhs = lhs, .rhs = rhs };\n");
    try w.writeAll("        out.len = @intCast(out.len + other.len + 1);\n");
    try w.writeAll("        out.root = out.len - 1;\n");
    try w.writeAll("        return out;\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn add(self: Self, other: Self) Self {\n");
    try w.writeAll("        return self.combine(other, .add);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn sub(self: Self, other: Self) Self {\n");
    try w.writeAll("        return self.combine(other, .sub);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn mul(self: Self, factor: f32) Self {\n");
    try w.writeAll("        return self.combine(numberLeaf(factor), .mul);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn div(self: Self, factor: f32) Self {\n");
    try w.writeAll("        return self.combine(numberLeaf(factor), .div);\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    fn renderNode(self: Self, index: u8, w: *std.io.Writer) !void {\n");
    try w.writeAll("        const node = self.nodes[index];\n");
    try w.writeAll("        switch (node.kind) {\n");
    try w.writeAll("            .unit => switch (node.unit) {\n");
    try w.writeAll("                .percent => try w.print(\"{d}%\", .{node.value}),\n");
    try w.writeAll("                else => try w.print(\"{d}{s}\", .{ node.value, @tagName(node.unit) }),\n");
    try w.writeAll("            },\n");
    try w.writeAll("            .number => try w.print(\"{d}\", .{node.value}),\n");
    try w.writeAll("            .raw => try w.writeAll(node.text),\n");
    try w.writeAll("            .op => {\n");
    try w.writeAll("                try w.writeByte('(');\n");
    try w.writeAll("                try self.renderNode(node.lhs, w);\n");
    try w.writeAll("                try w.print(\" {s} \", .{switch (node.op) { .add => \"+\", .sub => \"-\", .mul => \"*\", .div => \"/\" }});\n");
    try w.writeAll("                try self.renderNode(node.rhs, w);\n");
    try w.writeAll("                try w.writeByte(')');\n");
    try w.writeAll("            },\n");
    try w.writeAll("        }\n");
    try w.writeAll("    }\n");
    try w.writeAll("\n");
    try w.writeAll("    pub fn format(self: Self, w: *std.io.Writer) !void {\n");
    try w.writeAll("        try self.renderNode(self.root, w);\n");
    try w.writeAll("    }\n");
    try w.writeAll("};\n");

    return try out.toOwnedSlice(allocator);
}
