//! Generates `src/lsp/html_docs.zig` - a registry of HTML element and
//! attribute documentation used by the language server for hover tooltips.
//!
//! Downloads Microsoft's VS Code HTML custom data at build/gen time:
//!   https://raw.githubusercontent.com/microsoft/vscode-custom-data/refs/heads/main/web-data/data/browsers.html-data.json
//!
//! Run `zig build htmldocsgen` to regenerate (requires network).

const std = @import("std");

const data_url =
    "https://raw.githubusercontent.com/microsoft/vscode-custom-data/refs/heads/main/web-data/data/browsers.html-data.json";

fn eql(a: []const u8, b: []const u8) bool {
    return std.mem.eql(u8, a, b);
}

const ElementDoc = struct {
    name: []const u8,
    description: []const u8 = "",
    href: []const u8 = "",
};

const AttrDoc = struct {
    name: []const u8,
    /// "" means global.
    element: []const u8,
    description: []const u8 = "",
    href: []const u8 = "",
};

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    const source = try generate(io, allocator);
    defer allocator.free(source);
    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = "src/lsp/html_docs.zig",
        .data = source,
    });
    std.debug.print("Generated src/lsp/html_docs.zig\n", .{});
}

pub fn generate(io: std.Io, allocator: std.mem.Allocator) ![]const u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const a = arena_state.allocator();

    const json_bytes = try fetchJson(io, a);
    const parsed = try std.json.parseFromSlice(std.json.Value, a, json_bytes, .{});
    const root = parsed.value.object;

    var elements = std.StringHashMap(ElementDoc).init(a);
    var attrs: std.ArrayListUnmanaged(AttrDoc) = .empty;

    const tags = (root.get("tags") orelse return error.BadHtmlData).array;
    for (tags.items) |tag_val| {
        const tag = tag_val.object;
        const name = (tag.get("name") orelse continue).string;
        if (elements.contains(name)) continue;

        const href = firstReferenceUrl(tag.get("references"));
        const description = descriptionText(tag.get("description"));
        try elements.put(name, .{
            .name = name,
            .description = description,
            .href = href,
        });

        if (tag.get("attributes")) |attrs_val| {
            for (attrs_val.array.items) |attr_val| {
                const attr = attr_val.object;
                const attr_name = (attr.get("name") orelse continue).string;
                // Element-scoped attributes rarely carry their own references;
                // fall back to the element's MDN page.
                const attr_href = firstReferenceUrl(attr.get("references"));
                try attrs.append(a, .{
                    .name = attr_name,
                    .element = name,
                    .description = descriptionText(attr.get("description")),
                    .href = if (attr_href.len > 0) attr_href else href,
                });
            }
        }
    }

    if (root.get("globalAttributes")) |globals_val| {
        for (globals_val.array.items) |attr_val| {
            const attr = attr_val.object;
            const attr_name = (attr.get("name") orelse continue).string;
            try attrs.append(a, .{
                .name = attr_name,
                .element = "",
                .description = descriptionText(attr.get("description")),
                .href = firstReferenceUrl(attr.get("references")),
            });
        }
    }

    var out: std.Io.Writer.Allocating = .init(a);
    const w = &out.writer;

    try w.writeAll(
        \\//! Generated by tools/codegen/html_docs.zig - do not edit manually.
        \\//! Run `zig build htmldocsgen` to regenerate.
        \\//!
        \\//! HTML element/attribute documentation for language-server hover.
        \\//! Source: VS Code browsers.html-data.json (microsoft/vscode-custom-data).
        \\//! Lookups are ASCII case-insensitive.
        \\
        \\const std = @import("std");
        \\
        \\pub const ElementDoc = struct {
        \\    /// Tag name, e.g. "div".
        \\    name: []const u8,
        \\    /// Markdown/plain summary (may be empty).
        \\    description: []const u8 = "",
        \\    /// Link to MDN (or other reference; may be empty).
        \\    href: []const u8 = "",
        \\};
        \\
        \\pub const AttributeDoc = struct {
        \\    /// Attribute name, e.g. "href".
        \\    name: []const u8,
        \\    /// Markdown/plain summary (may be empty).
        \\    description: []const u8 = "",
        \\    /// Link to MDN (or other reference; may be empty).
        \\    href: []const u8 = "",
        \\};
        \\
        \\const Map = std.StaticStringMapWithEql(
        \\    ElementDoc,
        \\    std.static_string_map.eqlAsciiIgnoreCase,
        \\);
        \\
        \\const AttrMap = std.StaticStringMapWithEql(
        \\    AttributeDoc,
        \\    std.static_string_map.eqlAsciiIgnoreCase,
        \\);
        \\
        \\
    );

    try w.writeAll("const elements = Map.initComptime(.{\n");
    var el_keys: std.ArrayListUnmanaged([]const u8) = .empty;
    {
        var kit = elements.keyIterator();
        while (kit.next()) |k| try el_keys.append(a, k.*);
    }
    std.mem.sort([]const u8, el_keys.items, {}, lessThan);
    for (el_keys.items) |k| {
        const el = elements.get(k).?;
        try w.print("    .{{ \"{f}\", ElementDoc{{ .name = \"{f}\", .description = \"{f}\", .href = \"{f}\" }} }},\n", .{
            zigEscape(k), zigEscape(el.name), zigEscape(el.description), zigEscape(el.href),
        });
    }
    try w.writeAll("});\n\n");

    try w.writeAll("const global_attributes = AttrMap.initComptime(.{\n");
    {
        var global_keys: std.ArrayListUnmanaged([]const u8) = .empty;
        var seen = std.StringHashMap(void).init(a);
        for (attrs.items) |at| {
            if (at.element.len != 0) continue;
            if (seen.contains(at.name)) continue;
            try seen.put(at.name, {});
            try global_keys.append(a, at.name);
        }
        std.mem.sort([]const u8, global_keys.items, {}, lessThan);
        for (global_keys.items) |name| {
            const href = attrField(attrs.items, "", name, .href);
            const desc = attrField(attrs.items, "", name, .description);
            try w.print("    .{{ \"{f}\", AttributeDoc{{ .name = \"{f}\", .description = \"{f}\", .href = \"{f}\" }} }},\n", .{
                zigEscape(name), zigEscape(name), zigEscape(desc), zigEscape(href),
            });
        }
    }
    try w.writeAll("});\n\n");

    try w.writeAll("// Keyed by \"<element>\\t<attr>\" (lower-case element).\n");
    try w.writeAll("const element_attributes = AttrMap.initComptime(.{\n");
    {
        var keys: std.ArrayListUnmanaged([]const u8) = .empty;
        var seen = std.StringHashMap(void).init(a);
        for (attrs.items) |at| {
            if (at.element.len == 0) continue;
            const key = try std.fmt.allocPrint(a, "{s}\t{s}", .{ at.element, at.name });
            if (seen.contains(key)) continue;
            try seen.put(key, {});
            try keys.append(a, key);
        }
        std.mem.sort([]const u8, keys.items, {}, lessThan);
        for (keys.items) |key| {
            const tab = std.mem.indexOfScalar(u8, key, '\t').?;
            const element = key[0..tab];
            const attr = key[tab + 1 ..];
            const href = attrField(attrs.items, element, attr, .href);
            const desc = attrField(attrs.items, element, attr, .description);
            try w.print("    .{{ \"{f}\\t{f}\", AttributeDoc{{ .name = \"{f}\", .description = \"{f}\", .href = \"{f}\" }} }},\n", .{
                zigEscape(element), zigEscape(attr), zigEscape(attr), zigEscape(desc), zigEscape(href),
            });
        }
    }
    try w.writeAll("});\n\n");

    try w.writeAll(
        \\/// Look up documentation for an HTML element by tag name.
        \\pub fn element(name: []const u8) ?ElementDoc {
        \\    return elements.get(name);
        \\}
        \\
        \\/// Look up documentation for an attribute. Tries the element-specific
        \\/// definition first, then falls back to global attributes. Element and
        \\/// attribute name matching is ASCII case-insensitive (the underlying
        \\/// maps use eqlAsciiIgnoreCase), so the "<element>\t<attr>" key only
        \\/// needs the raw bytes joined.
        \\pub fn attribute(tag: []const u8, attr: []const u8) ?AttributeDoc {
        \\    var buf: [128]u8 = undefined;
        \\    if (tag.len + 1 + attr.len <= buf.len) {
        \\        @memcpy(buf[0..tag.len], tag);
        \\        buf[tag.len] = '\t';
        \\        @memcpy(buf[tag.len + 1 ..][0..attr.len], attr);
        \\        const key = buf[0 .. tag.len + 1 + attr.len];
        \\        if (element_attributes.get(key)) |d| return d;
        \\    }
        \\    return global_attributes.get(attr);
        \\}
        \\
    );

    return allocator.dupe(u8, out.written());
}

fn fetchJson(io: std.Io, allocator: std.mem.Allocator) ![]const u8 {
    var client: std.http.Client = .{ .allocator = allocator, .io = io };
    defer client.deinit();

    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();

    const result = client.fetch(.{
        .location = .{ .url = data_url },
        .method = .GET,
        .redirect_behavior = @enumFromInt(5),
        .response_writer = &aw.writer,
        .extra_headers = &.{
            .{ .name = "user-agent", .value = "ziex-htmldocsgen" },
            .{ .name = "accept", .value = "application/json" },
        },
    }) catch return error.NetworkError;

    if (result.status != .ok) return error.NetworkError;
    return try allocator.dupe(u8, aw.written());
}

fn descriptionText(value: ?std.json.Value) []const u8 {
    const v = value orelse return "";
    return switch (v) {
        .string => |s| s,
        .object => |o| if (o.get("value")) |inner| switch (inner) {
            .string => |s| s,
            else => "",
        } else "",
        else => "",
    };
}

fn firstReferenceUrl(value: ?std.json.Value) []const u8 {
    const v = value orelse return "";
    if (v != .array) return "";
    for (v.array.items) |ref| {
        if (ref != .object) continue;
        if (ref.object.get("url")) |url| {
            if (url == .string and url.string.len > 0) return url.string;
        }
    }
    return "";
}

const AttrField = enum { href, description };

fn attrField(items: []const AttrDoc, element: []const u8, name: []const u8, field: AttrField) []const u8 {
    for (items) |at| {
        if (!eql(at.name, name)) continue;
        if (!eql(at.element, element)) continue;
        return switch (field) {
            .href => at.href,
            .description => at.description,
        };
    }
    return "";
}

fn lessThan(_: void, l: []const u8, r: []const u8) bool {
    return std.mem.lessThan(u8, l, r);
}

/// Escapes a string for embedding inside a Zig `"..."` literal.
const ZigEscape = struct {
    s: []const u8,
    pub fn format(self: ZigEscape, w: *std.Io.Writer) !void {
        for (self.s) |c| switch (c) {
            '"' => try w.writeAll("\\\""),
            '\\' => try w.writeAll("\\\\"),
            '\n' => try w.writeAll("\\n"),
            '\r' => try w.writeAll("\\r"),
            '\t' => try w.writeAll("\\t"),
            else => try w.writeByte(c),
        };
    }
};

fn zigEscape(s: []const u8) ZigEscape {
    return .{ .s = s };
}
