const std = @import("std");
const Tag = @import("element").Tag;

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    var args = try std.process.Args.Iterator.initAllocator(init.minimal.args, allocator);
    defer args.deinit();
    _ = args.next(); // argv0
    const tags_path = args.next() orelse "src/wasm/generated/tags.ts";
    const indices_path = args.next() orelse "src/wasm/generated/tag_indices.ts";

    {
        var aw: std.Io.Writer.Allocating = .init(allocator);
        defer aw.deinit();
        try writeTagIndicesTs(&aw.writer);
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = indices_path, .data = aw.written() });
    }
    {
        var aw: std.Io.Writer.Allocating = .init(allocator);
        defer aw.deinit();
        try writeTagsTs(&aw.writer);
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = tags_path, .data = aw.written() });
    }

    std.debug.print("Generated {s} + {s} ({d} tags, svg_start={d}, custom={d})\n", .{
        tags_path,
        indices_path,
        @typeInfo(Tag).@"enum".field_names.len,
        @intFromEnum(Tag.svg_start),
        @intFromEnum(Tag.custom),
    });
}

/// Path-import-free integer module for esbuild const inlining.
pub fn writeTagIndicesTs(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\// AUTO-GENERATED by pkg/ziex/tools/gen_tags.zig.
        \\
    );
    try w.print("export const SVG_TAG_START_INDEX = {d};\n", .{@intFromEnum(Tag.svg_start)});
    try w.print("export const CUSTOM_TAG_INDEX = {d};\n", .{@intFromEnum(Tag.custom)});
}

pub fn writeTagsTs(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\// AUTO-GENERATED by pkg/ziex/tools/gen_tags.zig.
        \\
        \\export const TAG_NAMES = [
    );
    inline for (@typeInfo(Tag).@"enum".field_names) |name| {
        try w.print("    '{s}',\n", .{name});
    }
    try w.writeAll("] as const;\n");
}
