const std = @import("std");
const EventType = @import("event_type").EventType;

pub fn main(init: std.process.Init) !void {
    const allocator = init.gpa;
    const io = init.io;

    var args = try std.process.Args.Iterator.initAllocator(init.minimal.args, allocator);
    defer args.deinit();
    _ = args.next(); // argv0
    const events_path = args.next() orelse "src/wasm/generated/events.ts";
    const bits_path = args.next() orelse "src/wasm/generated/event_bits.ts";

    var bits: u32 = 0;
    inline for (@typeInfo(EventType).@"enum".field_names, 0..) |name, i| {
        const et: EventType = @field(EventType, name);
        if (et.isHighFreq()) bits |= @as(u32, 1) << @intCast(i);
    }

    {
        var aw: std.Io.Writer.Allocating = .init(allocator);
        defer aw.deinit();
        try writeEventBitsTs(&aw.writer, bits);
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = bits_path, .data = aw.written() });
    }
    {
        var aw: std.Io.Writer.Allocating = .init(allocator);
        defer aw.deinit();
        try writeEventsTs(&aw.writer);
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = events_path, .data = aw.written() });
    }

    std.debug.print("Generated {s} + {s} ({d} events, high_freq=0x{x})\n", .{
        events_path,
        bits_path,
        @typeInfo(EventType).@"enum".field_names.len,
        bits,
    });
}

/// Path-import-free integer module for esbuild const inlining.
fn writeEventBitsTs(w: *std.Io.Writer, bits: u32) !void {
    try w.writeAll(
        \\// AUTO-GENERATED by pkg/ziex/tools/gen_delegated_events.zig.
        \\/** High-frequency event type bitmask -> `(bits & (1 << id)) !== 0`. */
        \\
    );
    try w.print("export const HIGH_FREQ_EVENT_BITS = 0x{x};\n", .{bits});
}

fn writeEventsTs(w: *std.Io.Writer) !void {
    try w.writeAll(
        \\// AUTO-GENERATED by pkg/ziex/tools/gen_delegated_events.zig.
        \\// Source of truth: src/runtime/client/event_type.zig (`EventType`).
        \\// Regenerate: `zig build tagsgen` (root) or `zig build delegatedeventsgen` (pkg/ziex).
        \\
    );
    try w.writeAll("export const DELEGATED_EVENTS = [\n");
    inline for (@typeInfo(EventType).@"enum".field_names) |name| {
        const et: EventType = @field(EventType, name);
        try w.print("    '{s}',\n", .{et.domEventName()});
    }
    try w.writeAll("] as const;\n");
}
