/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 93
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 2
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_text = 1,
  aux_sym_whitespace_token1 = 2,
  sym_soft_line_break = 3,
  sym__text_inline_no_link = 4,
  aux_sym_code_span_token1 = 5,
  aux_sym_code_span_token2 = 6,
  anon_sym_STAR = 7,
  aux_sym_emphasis_token1 = 8,
  anon_sym__ = 9,
  aux_sym_emphasis_token2 = 10,
  anon_sym_STAR_STAR = 11,
  anon_sym___ = 12,
  anon_sym_STAR_STAR_STAR = 13,
  anon_sym____ = 14,
  anon_sym_TILDE_TILDE = 15,
  aux_sym_strikethrough_token1 = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  aux_sym_full_reference_link_token1 = 21,
  anon_sym_BANG = 22,
  anon_sym_LT = 23,
  aux_sym_link_destination_token1 = 24,
  anon_sym_GT = 25,
  aux_sym_link_destination_token2 = 26,
  anon_sym_DQUOTE = 27,
  anon_sym_SQUOTE = 28,
  aux_sym_autolink_token1 = 29,
  sym__backslash_escape = 30,
  sym__word = 31,
  sym_inline = 32,
  sym__inline_element = 33,
  sym_whitespace = 34,
  sym_code_span = 35,
  sym_emphasis = 36,
  sym_strong_emphasis = 37,
  sym_bold_italic = 38,
  sym_strikethrough = 39,
  sym_inline_link = 40,
  sym_link_text = 41,
  sym_full_reference_link = 42,
  sym_image = 43,
  sym_link_destination = 44,
  sym_link_title = 45,
  sym_autolink = 46,
  sym_backslash_escape = 47,
  sym__whitespace = 48,
  aux_sym_inline_repeat1 = 49,
  aux_sym_link_text_repeat1 = 50,
  aux_sym_link_title_repeat1 = 51,
  alias_sym_bold_italic_content = 52,
  alias_sym_strong_emphasis_content = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_text] = "text",
  [aux_sym_whitespace_token1] = "whitespace_token1",
  [sym_soft_line_break] = "soft_line_break",
  [sym__text_inline_no_link] = "link_text_content",
  [aux_sym_code_span_token1] = "code_span_delimiter",
  [aux_sym_code_span_token2] = "code_span_content",
  [anon_sym_STAR] = "*",
  [aux_sym_emphasis_token1] = "emphasis_content",
  [anon_sym__] = "_",
  [aux_sym_emphasis_token2] = "emphasis_content",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym___] = "__",
  [anon_sym_STAR_STAR_STAR] = "***",
  [anon_sym____] = "___",
  [anon_sym_TILDE_TILDE] = "~~",
  [aux_sym_strikethrough_token1] = "strikethrough_content",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [aux_sym_full_reference_link_token1] = "link_label",
  [anon_sym_BANG] = "!",
  [anon_sym_LT] = "<",
  [aux_sym_link_destination_token1] = "uri",
  [anon_sym_GT] = ">",
  [aux_sym_link_destination_token2] = "link_destination_token2",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_autolink_token1] = "uri",
  [sym__backslash_escape] = "_backslash_escape",
  [sym__word] = "_word",
  [sym_inline] = "inline",
  [sym__inline_element] = "_inline_element",
  [sym_whitespace] = "whitespace",
  [sym_code_span] = "code_span",
  [sym_emphasis] = "emphasis",
  [sym_strong_emphasis] = "strong_emphasis",
  [sym_bold_italic] = "bold_italic",
  [sym_strikethrough] = "strikethrough",
  [sym_inline_link] = "inline_link",
  [sym_link_text] = "link_text",
  [sym_full_reference_link] = "full_reference_link",
  [sym_image] = "image",
  [sym_link_destination] = "link_destination",
  [sym_link_title] = "link_title",
  [sym_autolink] = "autolink",
  [sym_backslash_escape] = "backslash_escape",
  [sym__whitespace] = "_whitespace",
  [aux_sym_inline_repeat1] = "inline_repeat1",
  [aux_sym_link_text_repeat1] = "link_text_repeat1",
  [aux_sym_link_title_repeat1] = "link_title_repeat1",
  [alias_sym_bold_italic_content] = "bold_italic_content",
  [alias_sym_strong_emphasis_content] = "strong_emphasis_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_text] = sym_text,
  [aux_sym_whitespace_token1] = aux_sym_whitespace_token1,
  [sym_soft_line_break] = sym_soft_line_break,
  [sym__text_inline_no_link] = sym__text_inline_no_link,
  [aux_sym_code_span_token1] = aux_sym_code_span_token1,
  [aux_sym_code_span_token2] = aux_sym_code_span_token2,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_emphasis_token1] = aux_sym_emphasis_token1,
  [anon_sym__] = anon_sym__,
  [aux_sym_emphasis_token2] = aux_sym_emphasis_token1,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym___] = anon_sym___,
  [anon_sym_STAR_STAR_STAR] = anon_sym_STAR_STAR_STAR,
  [anon_sym____] = anon_sym____,
  [anon_sym_TILDE_TILDE] = anon_sym_TILDE_TILDE,
  [aux_sym_strikethrough_token1] = aux_sym_strikethrough_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_full_reference_link_token1] = aux_sym_full_reference_link_token1,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LT] = anon_sym_LT,
  [aux_sym_link_destination_token1] = aux_sym_link_destination_token1,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_link_destination_token2] = aux_sym_link_destination_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_autolink_token1] = aux_sym_link_destination_token1,
  [sym__backslash_escape] = sym__backslash_escape,
  [sym__word] = sym__word,
  [sym_inline] = sym_inline,
  [sym__inline_element] = sym__inline_element,
  [sym_whitespace] = sym_whitespace,
  [sym_code_span] = sym_code_span,
  [sym_emphasis] = sym_emphasis,
  [sym_strong_emphasis] = sym_strong_emphasis,
  [sym_bold_italic] = sym_bold_italic,
  [sym_strikethrough] = sym_strikethrough,
  [sym_inline_link] = sym_inline_link,
  [sym_link_text] = sym_link_text,
  [sym_full_reference_link] = sym_full_reference_link,
  [sym_image] = sym_image,
  [sym_link_destination] = sym_link_destination,
  [sym_link_title] = sym_link_title,
  [sym_autolink] = sym_autolink,
  [sym_backslash_escape] = sym_backslash_escape,
  [sym__whitespace] = sym__whitespace,
  [aux_sym_inline_repeat1] = aux_sym_inline_repeat1,
  [aux_sym_link_text_repeat1] = aux_sym_link_text_repeat1,
  [aux_sym_link_title_repeat1] = aux_sym_link_title_repeat1,
  [alias_sym_bold_italic_content] = alias_sym_bold_italic_content,
  [alias_sym_strong_emphasis_content] = alias_sym_strong_emphasis_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_whitespace_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_soft_line_break] = {
    .visible = true,
    .named = true,
  },
  [sym__text_inline_no_link] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_span_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_span_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_emphasis_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_emphasis_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym___] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym____] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_TILDE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_strikethrough_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_full_reference_link_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_link_destination_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_link_destination_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_autolink_token1] = {
    .visible = true,
    .named = true,
  },
  [sym__backslash_escape] = {
    .visible = false,
    .named = true,
  },
  [sym__word] = {
    .visible = false,
    .named = true,
  },
  [sym_inline] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_element] = {
    .visible = false,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_code_span] = {
    .visible = true,
    .named = true,
  },
  [sym_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_emphasis] = {
    .visible = true,
    .named = true,
  },
  [sym_bold_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_strikethrough] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_link] = {
    .visible = true,
    .named = true,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [sym_full_reference_link] = {
    .visible = true,
    .named = true,
  },
  [sym_image] = {
    .visible = true,
    .named = true,
  },
  [sym_link_destination] = {
    .visible = true,
    .named = true,
  },
  [sym_link_title] = {
    .visible = true,
    .named = true,
  },
  [sym_autolink] = {
    .visible = true,
    .named = true,
  },
  [sym_backslash_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_text_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_link_title_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_bold_italic_content] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_strong_emphasis_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_strong_emphasis_content,
  },
  [2] = {
    [1] = alias_sym_bold_italic_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 6,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 6,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '!', 53,
        '"', 60,
        '\'', 61,
        '(', 47,
        ')', 48,
        '*', 31,
        '<', 54,
        '>', 58,
        '[', 49,
        '\\', 16,
        ']', 50,
        '_', 35,
        '`', 27,
        '~', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead == ']') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '`') ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '_') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == '\n') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '~') ADVANCE(46);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(61);
      if (lookahead == ')') ADVANCE(48);
      if (lookahead == '<') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(7);
      if (lookahead != 0 &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(59);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(8);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < ' ' || '/' < lookahead) &&
          (lookahead < ':' || '@' < lookahead) &&
          (lookahead < '[' || '`' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(65);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '_') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(38);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '_') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(62);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == ']') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 14:
      if (lookahead == '_') ADVANCE(40);
      END_STATE();
    case 15:
      if (lookahead == '~') ADVANCE(44);
      END_STATE();
    case 16:
      if (('!' <= lookahead && lookahead <= '/') ||
          (':' <= lookahead && lookahead <= '@') ||
          ('[' <= lookahead && lookahead <= '`') ||
          ('{' <= lookahead && lookahead <= '~')) ADVANCE(63);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 24,
        '!', 53,
        '*', 31,
        '<', 54,
        '[', 49,
        '\\', 16,
        '_', 35,
        '`', 27,
        '~', 15,
        '\t', 21,
        ' ', 21,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(20);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\n', 24,
        '!', 53,
        '*', 31,
        '<', 54,
        '[', 49,
        '\\', 16,
        '_', 35,
        '`', 27,
        '~', 15,
        '\t', 21,
        ' ', 21,
      );
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '!' &&
          lookahead != '*' &&
          lookahead != '<' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '_' &&
          lookahead != '`' &&
          lookahead != '~') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_whitespace_token1);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_whitespace_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_whitespace_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(64);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_soft_line_break);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__text_inline_no_link);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__text_inline_no_link);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          (lookahead < '[' || ']' < lookahead)) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_code_span_token1);
      if (lookahead == '`') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_code_span_token2);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '`') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_code_span_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '`') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(39);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_emphasis_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '*') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_emphasis_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '*') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym__);
      if (lookahead == '_') ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_emphasis_token2);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '_') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_emphasis_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '_') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      if (lookahead == '*') ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym___);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym___);
      if (lookahead == '_') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_STAR_STAR_STAR);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym____);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_TILDE_TILDE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_strikethrough_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '~') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_strikethrough_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '~') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_full_reference_link_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_full_reference_link_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_link_destination_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_link_destination_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_link_destination_token2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_autolink_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__backslash_escape);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__word);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(64);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          (lookahead < ' ' || '/' < lookahead) &&
          (lookahead < ':' || '@' < lookahead) &&
          (lookahead < '[' || '`' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__word);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          (lookahead < ' ' || '/' < lookahead) &&
          (lookahead < ':' || '@' < lookahead) &&
          (lookahead < '[' || '`' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 17},
  [3] = {.lex_state = 17},
  [4] = {.lex_state = 17},
  [5] = {.lex_state = 17},
  [6] = {.lex_state = 17},
  [7] = {.lex_state = 17},
  [8] = {.lex_state = 17},
  [9] = {.lex_state = 17},
  [10] = {.lex_state = 17},
  [11] = {.lex_state = 17},
  [12] = {.lex_state = 17},
  [13] = {.lex_state = 17},
  [14] = {.lex_state = 17},
  [15] = {.lex_state = 17},
  [16] = {.lex_state = 17},
  [17] = {.lex_state = 17},
  [18] = {.lex_state = 17},
  [19] = {.lex_state = 17},
  [20] = {.lex_state = 17},
  [21] = {.lex_state = 17},
  [22] = {.lex_state = 17},
  [23] = {.lex_state = 17},
  [24] = {.lex_state = 17},
  [25] = {.lex_state = 17},
  [26] = {.lex_state = 17},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 8},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 7},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 7},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 7},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 11},
  [69] = {.lex_state = 4},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 9},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 11},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 4},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_code_span_token1] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym___] = ACTIONS(1),
    [anon_sym_STAR_STAR_STAR] = ACTIONS(1),
    [anon_sym____] = ACTIONS(1),
    [anon_sym_TILDE_TILDE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_autolink_token1] = ACTIONS(1),
    [sym__backslash_escape] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_inline] = STATE(85),
    [sym__inline_element] = STATE(2),
    [sym_whitespace] = STATE(2),
    [sym_code_span] = STATE(2),
    [sym_emphasis] = STATE(2),
    [sym_strong_emphasis] = STATE(2),
    [sym_bold_italic] = STATE(2),
    [sym_strikethrough] = STATE(2),
    [sym_inline_link] = STATE(2),
    [sym_link_text] = STATE(64),
    [sym_full_reference_link] = STATE(2),
    [sym_image] = STATE(2),
    [sym_autolink] = STATE(2),
    [sym_backslash_escape] = STATE(2),
    [aux_sym_inline_repeat1] = STATE(2),
    [sym_text] = ACTIONS(3),
    [aux_sym_whitespace_token1] = ACTIONS(5),
    [sym_soft_line_break] = ACTIONS(3),
    [aux_sym_code_span_token1] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_STAR_STAR] = ACTIONS(13),
    [anon_sym___] = ACTIONS(15),
    [anon_sym_STAR_STAR_STAR] = ACTIONS(17),
    [anon_sym____] = ACTIONS(19),
    [anon_sym_TILDE_TILDE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(27),
    [sym__backslash_escape] = ACTIONS(29),
  },
  [STATE(2)] = {
    [sym__inline_element] = STATE(3),
    [sym_whitespace] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_bold_italic] = STATE(3),
    [sym_strikethrough] = STATE(3),
    [sym_inline_link] = STATE(3),
    [sym_link_text] = STATE(64),
    [sym_full_reference_link] = STATE(3),
    [sym_image] = STATE(3),
    [sym_autolink] = STATE(3),
    [sym_backslash_escape] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_text] = ACTIONS(33),
    [aux_sym_whitespace_token1] = ACTIONS(5),
    [sym_soft_line_break] = ACTIONS(33),
    [aux_sym_code_span_token1] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym__] = ACTIONS(11),
    [anon_sym_STAR_STAR] = ACTIONS(13),
    [anon_sym___] = ACTIONS(15),
    [anon_sym_STAR_STAR_STAR] = ACTIONS(17),
    [anon_sym____] = ACTIONS(19),
    [anon_sym_TILDE_TILDE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(27),
    [sym__backslash_escape] = ACTIONS(29),
  },
  [STATE(3)] = {
    [sym__inline_element] = STATE(3),
    [sym_whitespace] = STATE(3),
    [sym_code_span] = STATE(3),
    [sym_emphasis] = STATE(3),
    [sym_strong_emphasis] = STATE(3),
    [sym_bold_italic] = STATE(3),
    [sym_strikethrough] = STATE(3),
    [sym_inline_link] = STATE(3),
    [sym_link_text] = STATE(64),
    [sym_full_reference_link] = STATE(3),
    [sym_image] = STATE(3),
    [sym_autolink] = STATE(3),
    [sym_backslash_escape] = STATE(3),
    [aux_sym_inline_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_text] = ACTIONS(37),
    [aux_sym_whitespace_token1] = ACTIONS(40),
    [sym_soft_line_break] = ACTIONS(37),
    [aux_sym_code_span_token1] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(46),
    [anon_sym__] = ACTIONS(49),
    [anon_sym_STAR_STAR] = ACTIONS(52),
    [anon_sym___] = ACTIONS(55),
    [anon_sym_STAR_STAR_STAR] = ACTIONS(58),
    [anon_sym____] = ACTIONS(61),
    [anon_sym_TILDE_TILDE] = ACTIONS(64),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_BANG] = ACTIONS(70),
    [anon_sym_LT] = ACTIONS(73),
    [sym__backslash_escape] = ACTIONS(76),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [21] = 2,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [42] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [63] = 2,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [84] = 2,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [105] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [126] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [147] = 2,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [168] = 2,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [189] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [210] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [231] = 2,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(125), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [252] = 2,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [273] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [294] = 2,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [315] = 2,
    ACTIONS(139), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [336] = 2,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
    ACTIONS(145), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [357] = 2,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    ACTIONS(149), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [378] = 2,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(153), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [399] = 2,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(157), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [420] = 2,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
    ACTIONS(161), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [441] = 2,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [462] = 2,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 15,
      sym_text,
      aux_sym_whitespace_token1,
      sym_soft_line_break,
      aux_sym_code_span_token1,
      anon_sym_STAR,
      anon_sym__,
      anon_sym_STAR_STAR,
      anon_sym___,
      anon_sym_STAR_STAR_STAR,
      anon_sym____,
      anon_sym_TILDE_TILDE,
      anon_sym_LBRACK,
      anon_sym_BANG,
      anon_sym_LT,
      sym__backslash_escape,
  [483] = 9,
    ACTIONS(171), 1,
      aux_sym_whitespace_token1,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(175), 1,
      anon_sym_LT,
    ACTIONS(177), 1,
      aux_sym_link_destination_token2,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    STATE(40), 1,
      sym__whitespace,
    STATE(48), 1,
      sym_link_destination,
    STATE(49), 1,
      sym_link_title,
  [511] = 9,
    ACTIONS(175), 1,
      anon_sym_LT,
    ACTIONS(177), 1,
      aux_sym_link_destination_token2,
    ACTIONS(179), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(183), 1,
      aux_sym_whitespace_token1,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym__whitespace,
    STATE(46), 1,
      sym_link_destination,
    STATE(47), 1,
      sym_link_title,
  [539] = 4,
    ACTIONS(192), 1,
      sym__backslash_escape,
    ACTIONS(187), 2,
      aux_sym_whitespace_token1,
      sym__word,
    ACTIONS(190), 2,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
    STATE(29), 3,
      sym_backslash_escape,
      sym__whitespace,
      aux_sym_link_title_repeat1,
  [556] = 4,
    ACTIONS(197), 1,
      anon_sym_DQUOTE,
    ACTIONS(199), 1,
      sym__backslash_escape,
    ACTIONS(195), 2,
      aux_sym_whitespace_token1,
      sym__word,
    STATE(29), 3,
      sym_backslash_escape,
      sym__whitespace,
      aux_sym_link_title_repeat1,
  [572] = 4,
    ACTIONS(197), 1,
      anon_sym_SQUOTE,
    ACTIONS(199), 1,
      sym__backslash_escape,
    ACTIONS(195), 2,
      aux_sym_whitespace_token1,
      sym__word,
    STATE(29), 3,
      sym_backslash_escape,
      sym__whitespace,
      aux_sym_link_title_repeat1,
  [588] = 4,
    ACTIONS(199), 1,
      sym__backslash_escape,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    ACTIONS(201), 2,
      aux_sym_whitespace_token1,
      sym__word,
    STATE(30), 3,
      sym_backslash_escape,
      sym__whitespace,
      aux_sym_link_title_repeat1,
  [604] = 4,
    ACTIONS(199), 1,
      sym__backslash_escape,
    ACTIONS(203), 1,
      anon_sym_SQUOTE,
    ACTIONS(205), 2,
      aux_sym_whitespace_token1,
      sym__word,
    STATE(31), 3,
      sym_backslash_escape,
      sym__whitespace,
      aux_sym_link_title_repeat1,
  [620] = 6,
    ACTIONS(175), 1,
      anon_sym_LT,
    ACTIONS(177), 1,
      aux_sym_link_destination_token2,
    ACTIONS(207), 1,
      aux_sym_whitespace_token1,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym__whitespace,
    STATE(45), 1,
      sym_link_destination,
  [639] = 6,
    ACTIONS(175), 1,
      anon_sym_LT,
    ACTIONS(177), 1,
      aux_sym_link_destination_token2,
    ACTIONS(211), 1,
      aux_sym_whitespace_token1,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym__whitespace,
    STATE(44), 1,
      sym_link_destination,
  [658] = 4,
    ACTIONS(215), 1,
      sym__text_inline_no_link,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    ACTIONS(220), 1,
      sym__backslash_escape,
    STATE(36), 2,
      sym_backslash_escape,
      aux_sym_link_text_repeat1,
  [672] = 4,
    ACTIONS(223), 1,
      sym__text_inline_no_link,
    ACTIONS(225), 1,
      anon_sym_RBRACK,
    ACTIONS(227), 1,
      sym__backslash_escape,
    STATE(36), 2,
      sym_backslash_escape,
      aux_sym_link_text_repeat1,
  [686] = 4,
    ACTIONS(227), 1,
      sym__backslash_escape,
    ACTIONS(229), 1,
      sym__text_inline_no_link,
    ACTIONS(231), 1,
      anon_sym_RBRACK,
    STATE(37), 2,
      sym_backslash_escape,
      aux_sym_link_text_repeat1,
  [700] = 1,
    ACTIONS(89), 5,
      aux_sym_whitespace_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym__backslash_escape,
      sym__word,
  [708] = 4,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    ACTIONS(237), 1,
      anon_sym_SQUOTE,
    STATE(51), 1,
      sym_link_title,
  [721] = 4,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    ACTIONS(237), 1,
      anon_sym_SQUOTE,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_link_title,
  [734] = 4,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    ACTIONS(237), 1,
      anon_sym_SQUOTE,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_link_title,
  [747] = 4,
    ACTIONS(235), 1,
      anon_sym_DQUOTE,
    ACTIONS(237), 1,
      anon_sym_SQUOTE,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_link_title,
  [760] = 3,
    ACTIONS(171), 1,
      aux_sym_whitespace_token1,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym__whitespace,
  [770] = 3,
    ACTIONS(183), 1,
      aux_sym_whitespace_token1,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym__whitespace,
  [780] = 3,
    ACTIONS(245), 1,
      aux_sym_whitespace_token1,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      sym__whitespace,
  [790] = 3,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    ACTIONS(249), 1,
      aux_sym_whitespace_token1,
    STATE(65), 1,
      sym__whitespace,
  [800] = 3,
    ACTIONS(251), 1,
      aux_sym_whitespace_token1,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      sym__whitespace,
  [810] = 3,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    ACTIONS(255), 1,
      aux_sym_whitespace_token1,
    STATE(76), 1,
      sym__whitespace,
  [820] = 3,
    ACTIONS(257), 1,
      aux_sym_whitespace_token1,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym__whitespace,
  [830] = 3,
    ACTIONS(261), 1,
      aux_sym_whitespace_token1,
    ACTIONS(263), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      sym__whitespace,
  [840] = 3,
    ACTIONS(265), 1,
      aux_sym_whitespace_token1,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      sym__whitespace,
  [850] = 3,
    ACTIONS(269), 1,
      aux_sym_whitespace_token1,
    ACTIONS(271), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym__whitespace,
  [860] = 2,
    ACTIONS(87), 1,
      sym__text_inline_no_link,
    ACTIONS(89), 2,
      anon_sym_RBRACK,
      sym__backslash_escape,
  [868] = 2,
    ACTIONS(273), 1,
      anon_sym_RBRACK,
    ACTIONS(275), 1,
      aux_sym_full_reference_link_token1,
  [875] = 1,
    ACTIONS(277), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [880] = 2,
    ACTIONS(279), 1,
      aux_sym_whitespace_token1,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
  [887] = 2,
    ACTIONS(283), 1,
      aux_sym_whitespace_token1,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
  [894] = 2,
    ACTIONS(287), 1,
      aux_sym_whitespace_token1,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [901] = 2,
    ACTIONS(291), 1,
      aux_sym_code_span_token1,
    ACTIONS(293), 1,
      aux_sym_code_span_token2,
  [908] = 2,
    ACTIONS(295), 1,
      anon_sym_LBRACK,
    STATE(73), 1,
      sym_link_text,
  [915] = 2,
    ACTIONS(297), 1,
      aux_sym_whitespace_token1,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
  [922] = 1,
    ACTIONS(301), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [927] = 2,
    ACTIONS(303), 1,
      anon_sym_LPAREN,
    ACTIONS(305), 1,
      anon_sym_LBRACK,
  [934] = 1,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
  [938] = 1,
    ACTIONS(307), 1,
      aux_sym_emphasis_token1,
  [942] = 1,
    ACTIONS(309), 1,
      anon_sym_STAR_STAR,
  [946] = 1,
    ACTIONS(311), 1,
      anon_sym_STAR,
  [950] = 1,
    ACTIONS(313), 1,
      aux_sym_emphasis_token2,
  [954] = 1,
    ACTIONS(315), 1,
      aux_sym_emphasis_token2,
  [958] = 1,
    ACTIONS(317), 1,
      aux_sym_strikethrough_token1,
  [962] = 1,
    ACTIONS(319), 1,
      anon_sym_TILDE_TILDE,
  [966] = 1,
    ACTIONS(321), 1,
      anon_sym_LPAREN,
  [970] = 1,
    ACTIONS(309), 1,
      anon_sym___,
  [974] = 1,
    ACTIONS(323), 1,
      anon_sym_GT,
  [978] = 1,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
  [982] = 1,
    ACTIONS(325), 1,
      aux_sym_autolink_token1,
  [986] = 1,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
  [990] = 1,
    ACTIONS(329), 1,
      anon_sym_RBRACK,
  [994] = 1,
    ACTIONS(331), 1,
      aux_sym_emphasis_token1,
  [998] = 1,
    ACTIONS(333), 1,
      anon_sym_GT,
  [1002] = 1,
    ACTIONS(311), 1,
      anon_sym__,
  [1006] = 1,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
  [1010] = 1,
    ACTIONS(337), 1,
      anon_sym_STAR_STAR_STAR,
  [1014] = 1,
    ACTIONS(339), 1,
      ts_builtin_sym_end,
  [1018] = 1,
    ACTIONS(341), 1,
      anon_sym_RPAREN,
  [1022] = 1,
    ACTIONS(343), 1,
      aux_sym_code_span_token1,
  [1026] = 1,
    ACTIONS(345), 1,
      anon_sym_RPAREN,
  [1030] = 1,
    ACTIONS(347), 1,
      aux_sym_emphasis_token2,
  [1034] = 1,
    ACTIONS(349), 1,
      aux_sym_emphasis_token1,
  [1038] = 1,
    ACTIONS(337), 1,
      anon_sym____,
  [1042] = 1,
    ACTIONS(351), 1,
      aux_sym_link_destination_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 21,
  [SMALL_STATE(6)] = 42,
  [SMALL_STATE(7)] = 63,
  [SMALL_STATE(8)] = 84,
  [SMALL_STATE(9)] = 105,
  [SMALL_STATE(10)] = 126,
  [SMALL_STATE(11)] = 147,
  [SMALL_STATE(12)] = 168,
  [SMALL_STATE(13)] = 189,
  [SMALL_STATE(14)] = 210,
  [SMALL_STATE(15)] = 231,
  [SMALL_STATE(16)] = 252,
  [SMALL_STATE(17)] = 273,
  [SMALL_STATE(18)] = 294,
  [SMALL_STATE(19)] = 315,
  [SMALL_STATE(20)] = 336,
  [SMALL_STATE(21)] = 357,
  [SMALL_STATE(22)] = 378,
  [SMALL_STATE(23)] = 399,
  [SMALL_STATE(24)] = 420,
  [SMALL_STATE(25)] = 441,
  [SMALL_STATE(26)] = 462,
  [SMALL_STATE(27)] = 483,
  [SMALL_STATE(28)] = 511,
  [SMALL_STATE(29)] = 539,
  [SMALL_STATE(30)] = 556,
  [SMALL_STATE(31)] = 572,
  [SMALL_STATE(32)] = 588,
  [SMALL_STATE(33)] = 604,
  [SMALL_STATE(34)] = 620,
  [SMALL_STATE(35)] = 639,
  [SMALL_STATE(36)] = 658,
  [SMALL_STATE(37)] = 672,
  [SMALL_STATE(38)] = 686,
  [SMALL_STATE(39)] = 700,
  [SMALL_STATE(40)] = 708,
  [SMALL_STATE(41)] = 721,
  [SMALL_STATE(42)] = 734,
  [SMALL_STATE(43)] = 747,
  [SMALL_STATE(44)] = 760,
  [SMALL_STATE(45)] = 770,
  [SMALL_STATE(46)] = 780,
  [SMALL_STATE(47)] = 790,
  [SMALL_STATE(48)] = 800,
  [SMALL_STATE(49)] = 810,
  [SMALL_STATE(50)] = 820,
  [SMALL_STATE(51)] = 830,
  [SMALL_STATE(52)] = 840,
  [SMALL_STATE(53)] = 850,
  [SMALL_STATE(54)] = 860,
  [SMALL_STATE(55)] = 868,
  [SMALL_STATE(56)] = 875,
  [SMALL_STATE(57)] = 880,
  [SMALL_STATE(58)] = 887,
  [SMALL_STATE(59)] = 894,
  [SMALL_STATE(60)] = 901,
  [SMALL_STATE(61)] = 908,
  [SMALL_STATE(62)] = 915,
  [SMALL_STATE(63)] = 922,
  [SMALL_STATE(64)] = 927,
  [SMALL_STATE(65)] = 934,
  [SMALL_STATE(66)] = 938,
  [SMALL_STATE(67)] = 942,
  [SMALL_STATE(68)] = 946,
  [SMALL_STATE(69)] = 950,
  [SMALL_STATE(70)] = 954,
  [SMALL_STATE(71)] = 958,
  [SMALL_STATE(72)] = 962,
  [SMALL_STATE(73)] = 966,
  [SMALL_STATE(74)] = 970,
  [SMALL_STATE(75)] = 974,
  [SMALL_STATE(76)] = 978,
  [SMALL_STATE(77)] = 982,
  [SMALL_STATE(78)] = 986,
  [SMALL_STATE(79)] = 990,
  [SMALL_STATE(80)] = 994,
  [SMALL_STATE(81)] = 998,
  [SMALL_STATE(82)] = 1002,
  [SMALL_STATE(83)] = 1006,
  [SMALL_STATE(84)] = 1010,
  [SMALL_STATE(85)] = 1014,
  [SMALL_STATE(86)] = 1018,
  [SMALL_STATE(87)] = 1022,
  [SMALL_STATE(88)] = 1026,
  [SMALL_STATE(89)] = 1030,
  [SMALL_STATE(90)] = 1034,
  [SMALL_STATE(91)] = 1038,
  [SMALL_STATE(92)] = 1042,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image, 9, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image, 9, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backslash_escape, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backslash_escape, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_emphasis, 3, 1, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_emphasis, 3, 1, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong_emphasis, 3, 2, 1),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong_emphasis, 3, 2, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bold_italic, 3, 5, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bold_italic, 3, 5, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strikethrough, 3, 2, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strikethrough, 3, 2, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_autolink, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_autolink, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_link, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_link, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_reference_link, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_reference_link, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_span, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_span, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_link, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_link, 4, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_full_reference_link, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_full_reference_link, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image, 5, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image, 5, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_link, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_link, 5, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image, 6, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image, 6, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_link, 6, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_link, 6, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image, 7, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image, 7, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_link, 7, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_link, 7, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image, 8, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image, 8, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_link, 8, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_link, 8, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whitespace, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_whitespace, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_title_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_link_title_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_title_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0),
  [220] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_link_text_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_text, 2, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_destination, 3, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_destination, 3, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_title, 2, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_title, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_destination, 1, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_destination, 1, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_title, 3, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link_title, 3, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link_text, 3, 0, 0),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [339] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mdzx_inline(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mdzx_inline",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
